### ISSUE TITLE
Dll from nuget package is not loading in NET Core 2.1

### ISSUE THREAD

**Issue by leevva** [VladimirRybalko/CSharpMongoMigrations#10]
It seems that something wrong with nuget package.
When i reference it in NET Core 2.1 project it doesn't show dll included and CSharpMongoMigrations is not listed in Object Browser.
![image](https://user-images.githubusercontent.com/14993476/52934351-9d99ce80-336f-11e9-8f76-df2ea1d065c0.png)

When i build nuget package from source code myself all is good.

**Comment by VladimirRybalko** [comment]
Hm. This is interesting. I'll have a look.

**Comment by VladimirRybalko** [comment]
Thank you @leevva for reporting it.
The issue was in the original nuspec file. The thing is the package was deployed as development dependency. Sorry for that. 
I've fixed it. Now, everything is well and you can download the latest 2.1.2 version.
