### ISSUE TITLE
Prefix of MitrationVersion Collection

### ISSUE THREAD

**Issue by lprada** [VladimirRybalko/CSharpMongoMigrations#12]
HI, what we need is the posibility to shared the same dabatase between differents microservicies. For this I need that a prefix can be add to the MigrationVersion Collection or have another parameter so I can migrate diferentes schemas in the database.

**Comment by VladimirRybalko** [comment]
Hello @lprada.
Thank you for your feedback.

The version 2.2.0 is what you need. 
I've added the collection specific migrations there. So, now you have much more control how to apply different migrations. 

In your particular case, please review the following example. 
Here, I create a specific migration for the *Animals* migration. 

```csharp
   [Migration("Animals", 0)]
    public sealed class AddAnimalMigration : Migration
    {
        public override void Up()
        {
            var collection = GetCollection("Animals");
            var document = new BsonDocument();

            document.AddUniqueIdentifier(new Guid("2A7B73A8-3C4A-422D-90B4-C73BCF48EBD4"));
            document.AddProperty("Kind", "Cat");

            collection.InsertOne(document);
        }

        public override void Down()
        {
            var collection = GetCollection("Animals");
            var idFilter = Builders<BsonDocument>.Filter.Eq("_id", new Guid("2A7B73A8-3C4A-422D-90B4-C73BCF48EBD4"));
            collection.DeleteOne(idFilter);
        }
    }
```

Then, what you need is just initiate the runner class and applied all migrations for the specific collection.

```csharp
   var runner = new MigrationRunner("mongodb://localhost:27017/TestMigrations", Assembly.GetExecutingAssembly().FullName, new MigrationFactory());
    runner.Up("Animals");
```
