### ISSUE TITLE
Add or change MigrationRunner constructor

### ISSUE THREAD

**Issue by ilyabreev** [VladimirRybalko/CSharpMongoMigrations#2]
`MigrationRunner` constructor now has following signature:

```c#
public MigrationRunner(string server, string database, string migrationAssembly)
```

I'd like to propose constructor that accepts `MongoUrl` as the convenient way to define mongo db connection string.

It might look like:
```c#
public MigrationRunner(MongoUrl connectionString, string migrationAssembly)
```

**Motivation**:
If I have a valid connection string for mongodb somewhere in my project in format _mongodb://..._ then I need to replace _mongodb://_ with empty string before passing it in `MigrationRunner`.

**Comment by VladimirRybalko** [comment]
Hi @ilyabreev 
Thank you for your request.
It makes sense. I like it. If you feel power to create a PR, feel free to do it. In other case I will have a look later.

**Comment by ilyabreev** [comment]
Hi @VladimirRybalko 
Can you please check a PR? Does it fit your project well?

**Comment by VladimirRybalko** [comment]
Hi @ilyabreev 
I've left my review. Could you please have a look?

**Comment by ilyabreev** [comment]
Thanks for cooperation.
Will you upload a new version of nuget package?

**Comment by VladimirRybalko** [comment]
Yes, I will.
It It will be soon.

**Comment by ilyabreev** [comment]
Just a friendly reminder that you promised to update nuget package
