### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MathieuMathurin** [VladimirRybalko/CSharpMongoMigrations#4]
I've found your repository by using your NuGet Package and I would like to use it for a commercial project, but there is currently no license in your repository which implies that I can't use it.

**Comment by VladimirRybalko** [comment]
Hello @MathieuMathurin .
Thank you for using my package. 
Feel free to use it for any kind of projects (including any commercial software).
I've added MIT license.

**Comment by MathieuMathurin** [comment]
Thank you for the quick response it's really appreciated!
