### ISSUE TITLE
nuget.org 2.1 package contains 2.0 assembly

### ISSUE THREAD

**Issue by nbalakin** [VladimirRybalko/CSharpMongoMigrations#7]
Hi.
The assemblies uploaded to nuget.org as 2.1 package has 2.0 version and there is no updates related to MongoUrl and stuff.

**Comment by VladimirRybalko** [comment]
Thank you, @nbalakin, for reporting the issue. 
I'll check it.

**Comment by VladimirRybalko** [comment]
It has been fixed. The new package is in a nuget feed.
